version: '3'

networks:
  mybridge:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - mybridge
    depends_on:
      - db

  db:
    image: postgres
    networks:
      - mybridge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
